### ISSUE TITLE
Writing accessible code

### ISSUE THREAD

**Issue by gpeterson406** [Kevin-Morales/Accessible-Web-Development#1]
Thank you for your book on accessible web development using bookdown.

I am the editor of an open source book on intermediate statistics and we cover writing R code. Do you have any suggestions for how to write books talking about code and output that will work with screen readers? Specifically all of the spaces used to line up output in a plain text table.

**Comment by Kevin-Morales** [comment]
I have a couple of suggestions.
You could write up your information for your tables using an R data frame, and use a package like kable to generate the appropriate markdown.
You could then use the R Markdown options for code chunks to hide the code fragment that generated the table.
Also, if you can make sure that the book be distributed in HTML for the best accessibility experience, that would be great.
I'd be happy to contribute or answer more questions because that project sounds promising.

Many Thanks,
Kevin

**Comment by gpeterson406** [comment]
Kevin, you can contact me at greta.linse@montana.edu and then we can close this issue. Will be easier to communicate. Thanks!
Greta
